cfg:
  data:
    task: mof_sp
    dataset: cif_200_inf
    cache_dir: /mnt/data/private/jr/projects/MOF-BFN/notebooks/datasets/mof_csp
    loader:
      num_workers: 4
      prefetch_factor: 10
    sampler:
      max_batch_size: 512
      batch_strategy: simple
      collate_fn: pyg
  experiment:
    debug: false
    seed: 123
    num_devices: 8
    warm_start: null
    warm_start_cfg_override: true
    training:
      mask_plddt: true
      bb_atom_scale: 0.1
      trans_scale: 0.1
      translation_loss_weight: 2.0
      t_normalize_clip: 0.9
      rotation_loss_weights: 1.0
      aux_loss_weight: 0.0
      aux_loss_use_bb_loss: true
      aux_loss_use_pair_loss: true
      aux_loss_t_pass: 0.5
      cell_scale: 0.1
      cell_loss_weight: 0.1
    wandb:
      name: infer_csp
      project: mof-csp
      save_dir: /mnt/data/private/jr/projects/aliyunpan-v0.3.7-linux-amd64/Downloads/a5defc2ced5540da84141924e18a4aaf/mofbfn/MOF-BFN/usefulckpts/logs
    wandb_watch:
      log: all
      log_freq: 500
    optimizer:
      lr: 0.0005
      betas:
      - 0.9
      - 0.98
      eps: 1.0e-08
      weight_decay: 0.01
    use_lr_scheduler: true
    lr_scheduler:
      factor: 0.6
      patience: 30
      min_lr: 0.0001
    trainer:
      overfit_batches: 0
      min_epochs: 1
      max_epochs: 1000
      accelerator: gpu
      log_every_n_steps: 1
      deterministic: false
      strategy: ddp
      val_check_interval: null
      check_val_every_n_epoch: 1
      accumulate_grad_batches: 1
      gradient_clip_val: 0.5
    checkpointer:
      dirpath: ./
      save_last: true
      save_top_k: 5
      monitor: val_loss
      filename: epoch_{epoch}-step_{step}-loss_{val_loss:.4f}
      auto_insert_metric_name: false
      mode: min
    inference_dir: /mnt/data/private/jr/projects/MOF-BFN/output
  matcher:
    stol: 0.5
    angle_tol: 10.0
    ltol: 0.3
  ema:
    enable: false
    decay: 0.995
  model:
    time_dim: 128
    hidden_dim: 256
    latent_dim: 256
    fc_num_layers: 1
    cost_natom: 1.0
    cost_coord: 1.0
    cost_type: 10.0
    cost_rot: 10.0
    cost_lattice: 1
    cost_composition: 1.0
    cost_edge: 10.0
    cost_property: 1.0
    beta: 0.01
    teacher_forcing_lattice: true
    max_neighbors: 20
    radius: 7.0
    sigma_begin: 0.5
    sigma_end: 0.005
    type_sigma_begin: 5.0
    type_sigma_end: 0.01
    num_noise_level: 50
    predict_property: true
    T_min: -np.pi
    T_max: np.pi
    norm_weight: false
    norm_beta: true
    rej_samp: false
    n_samples: 1
    BFN:
      _target_: models.crysbfn_csp_bhm.CrysBFN_CSP
      beta1_type: 0.5
      beta1_coord: 1000.0
      beta1_rot: 200
      t_min: 1.0e-07
      dtime_loss: true
      dtime_loss_steps: 50
      sigma1_lattice: 0.03162277660168379
      mult_constant: true
      pred_mean: true
      end_back: true
      sim_cir_flow: true
      cond_acc: true
      sch_type: linear
      disc_prob_loss: false
    decoder:
      _target_: models.cspnet_bfn.CSPNet
      hidden_dim: 512
      time_dim: 128
      bb_emb_dim: 64
      num_layers: 6
      num_freqs: 64
      max_neighbors: 20
      cutoff: 7.0
      ln: true
      period: np.pi--np.pi
      dtime_loss: true
      cond_acc: true
      so3_embedding_type: quat_bhm
    bb_embedder:
      c_node_dim: 64
      c_edge_dim: 64
      c_hidden_dim: 64
      max_atoms: 100
      max_radius: 5
      num_layers: 4
  paths:
    root_dir: /mnt/data/private/jr/projects/MOF-BFN
    save_dir: /mnt/data/private/jr/projects/aliyunpan-v0.3.7-linux-amd64/Downloads/a5defc2ced5540da84141924e18a4aaf/mofbfn/MOF-BFN/usefulckpts
    log_dir: /mnt/data/private/jr/projects/aliyunpan-v0.3.7-linux-amd64/Downloads/a5defc2ced5540da84141924e18a4aaf/mofbfn/MOF-BFN/usefulckpts/logs/mof-csp/infer_csp
    wandb_dir: /mnt/data/private/jr/projects/aliyunpan-v0.3.7-linux-amd64/Downloads/a5defc2ced5540da84141924e18a4aaf/mofbfn/MOF-BFN/usefulckpts/logs
    ckpt_dir: /mnt/data/private/jr/projects/aliyunpan-v0.3.7-linux-amd64/Downloads/a5defc2ced5540da84141924e18a4aaf/mofbfn/MOF-BFN/usefulckpts/logs/mof-csp/infer_csp/ckpt
    inference_dir: /mnt/data/private/jr/projects/aliyunpan-v0.3.7-linux-amd64/Downloads/a5defc2ced5540da84141924e18a4aaf/mofbfn/MOF-BFN/usefulckpts/logs/mof-csp/infer_csp/inference
    data_dir: /mnt/data/private/jr/projects/MOF-BFN/notebooks/datasets/mof_csp
    data_dng_dir: /mnt/data/private/jr/projects/MOF-BFN/notebooks/datasets/mof_csp
  lattice:
    lognormal:
      loc:
      - 2.5542190074920654
      - 2.754688262939453
      - 2.9632623195648193
      scale:
      - 0.37387514114379883
      - 0.30108675360679626
      - 0.31256887316703796
  inference:
    inference_dir: /mnt/data/private/jr/projects/MOF-BFN/output
    name: run_2026-01-08_14-28
    seed: 123
    task: null
    output_dir: inference_outputs/
    ckpt_path: /mnt/data/private/jr/projects/aliyunpan-v0.3.7-linux-amd64/Downloads/a5defc2ced5540da84141924e18a4aaf/mofbfn/MOF-BFN/usefulckpts/cspbfn_rot_lr_5e-4_bhm_w10/ckpt/last.ckpt
    use_gpu: true
    num_gpus: 1
    samples:
      samples_per_length: 10
      min_length: 60
      max_length: 128
      length_step: 1
      length_subset: null
      overwrite: false
      csv_path: motif_scaffolding/benchmark.csv
      samples_per_target: 100
      num_batch: 1
      target_subset: null
device: cuda:0
